version: '2'
networks:
  net:
services:
  server:
    image: dynovski/sir:multiarch
    container_name: sir_server
    restart: unless-stopped
    ports:
     - 80:16000
    networks:
     - net
  client:
    image: dynovski/sir_app:localhost
    container_name: sir_client
    restart: unless-stopped
    ports:
     - 16080:80
    networks:
     - net